[package]
name = "sui-tool"
version = "0.6.2"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.58", features = ["backtrace"] }
tokio = { version = "1.20.1", features = ["full"] }
tracing = "0.1.36"
clap = { version = "3.1.17", features = ["derive"] }
telemetry-subscribers = { git = "https://github.com/MystenLabs/mysten-infra", rev = "a4c2cae59d823533061a5d8fe28771629819c43f" }
mysten-network = { git = "https://github.com/MystenLabs/mysten-infra", rev = "a4c2cae59d823533061a5d8fe28771629819c43f" }
textwrap = "0.15"
futures = "0.3.21"
rocksdb = "0.18.0"
typed-store = { git = "https://github.com/MystenLabs/mysten-infra", rev = "a4c2cae59d823533061a5d8fe28771629819c43f"}
typed-store-macros = { git = "https://github.com/MystenLabs/mysten-infra", rev = "a4c2cae59d823533061a5d8fe28771629819c43f"} 
tempfile = "3.3.0"
narwhal-executor = { git = "https://github.com/MystenLabs/narwhal", rev = "259a37b487570763575e6b28f8b8057b16b3e916", package = "executor" }
serde_with = { version = "1.14.0", features = ["hex"] }
sui-storage = { path = "../sui-storage" }
strum_macros = "^0.24"
strum = "0.24.1"
serde = { version = "1.0.141", features = ["derive"] }

sui-core = { path = "../sui-core" }
sui-config = { path = "../sui-config" }
sui-types = { path = "../sui-types" }

colored = "2.0.0"
workspace-hack = { path = "../workspace-hack"}
